---
- hosts: all
  become: yes
  tasks:
   - name: remove Java
     shell: yum remove *java*
   - name: install java
     yum:
       name: java*1.8*
       state: present
       update_cache: true

   - name: copy Artifact
     copy:
       src: "{{ WORKSPACE }}/target/spring-petclinic-2.0.0.BUILD-SNAPSHOT.jar"
       dest: /tmp/petclinic.jar

   - name: start the petclinic

     shell: "nohup java -jar /tmp/petclinic.jar &"
